### ISSUE TITLE
Add dataset with python script

### ISSUE THREAD

**Issue by mohamedsto7y** [weecology/retriever-recipes#105]
I encountered `ModuleNotFoundError: No module named 'retriever'`  when I added a script named 'west_nile.py' to scripts folder to download a dataset although it is normally imported via python shell.

![retrr](https://user-images.githubusercontent.com/34280108/113522956-03279400-95a5-11eb-9b52-c86b3351e8d6.PNG)
![ss](https://user-images.githubusercontent.com/34280108/113522959-09b60b80-95a5-11eb-805d-adfe428687b1.PNG)

**Comment by henrykironde** [comment]
We do not run the script directly. We add it to the script directory, retriever then loads it.
You can create a PR for that script so that I can take a look at it.
