### ISSUE TITLE
Crop Progress Dataset Brazil

### ISSUE THREAD

**Issue by FrancyJGLisboa** [weecology/retriever-recipes#143]
Hi. I'd like to add crop progress from Brazil https://www.conab.gov.br/info-agro/safras/progresso-de-safra/item/download/45273_6bfd84e6d90df2ff7f26baec3d74cb49 and have no idea how to start LOL.
Any help?

**Comment by henrykironde** [comment]
@FrancyJGLisboa thank you for the data request. Unfortunately, the data "Plantio e colheita" is a report. If you know the original data, we are happy to help you get the data using the Data Retriever platform. Let us know if you have any other data requests.
