### ISSUE TITLE
Link broken of Data Retriever website in Readme .

### ISSUE THREAD

**Issue by Mohitkumar6122** [weecology/retriever-recipes#95]
Currently the link of the Data Retriever website in the readme page of retriever-recipes. <br>
![IMAGE](https://i.ibb.co/cv8Q1Xd/Screenshot-2021-03-15-011612.png) <br>
**To fix this issue we need to change the link of retriever org to its official docs as stated in Retriever readme.**

**Comment by henrykironde** [comment]
Solved
